### ISSUE TITLE
is there a problem, iam new to node

### ISSUE THREAD

**Issue by goog** [momenso/node-dht-sensor#37]
```bash
pi@raspberrypi:~ $ sudo npm install -g node-dht-sensor
/
> node-dht-sensor@0.0.11 preinstall /usr/local/lib/node_modules/node-dht-sensor
> ./preinst

Library bcm2835 found.
Installing Native Abstractions for Node.js (NAN)...
npm ERR! Error: Attempt to unlock nan, which hasn't been locked
npm ERR!     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
npm ERR!     at cb (/usr/share/npm/lib/cache/add-local.js:30:5)
npm ERR!     at /usr/share/npm/lib/cache/add-local.js:47:20
npm ERR!     at /usr/share/npm/lib/utils/locker.js:22:20
npm ERR!     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
npm ERR!     at Array.forEach (native)
npm ERR!     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
npm ERR!     at /usr/lib/nodejs/once.js:17:15
npm ERR!     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
npm ERR!     at /usr/lib/nodejs/mkdirp/index.js:46:53
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.1.19-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "nan"
npm ERR! cwd /usr/local/lib/node_modules/node-dht-sensor
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/node-dht-sensor/npm-debug.log
npm ERR! not ok code 0
Rebuiling addon...
make: Entering directory '/usr/local/lib/node_modules/node-dht-sensor/build'
  CXX(target) Release/obj.target/node_dht_sensor/node-dht-sensor.o
  SOLINK_MODULE(target) Release/obj.target/node_dht_sensor.node
  SOLINK_MODULE(target) Release/obj.target/node_dht_sensor.node: Finished
  COPY Release/node_dht_sensor.node
make: Leaving directory '/usr/local/lib/node_modules/node-dht-sensor/build'
node-dht-sensor@0.0.11 /usr/local/lib/node_modules/node-dht-sensor
└── nan@2.2.1
```

**Comment by goog** [comment]
i have installed the nan by 
```bash
sudo npm install -g nan
nan@2.2.1 /usr/local/lib/node_modules/nan
```

pi@raspberrypi:~ $ cat /usr/local/lib/node_modules/node-dht-sensor/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'install', 'nan' ]
2 info using npm@1.4.21
3 info using node@v0.10.29
4 verbose cache add [ 'nan', null ]
5 verbose cache add name=undefined spec="nan" args=["nan",null]
6 verbose parsed url { protocol: null,
6 verbose parsed url   slashes: null,
6 verbose parsed url   auth: null,
6 verbose parsed url   host: null,
6 verbose parsed url   port: null,
6 verbose parsed url   hostname: null,
6 verbose parsed url   hash: null,
6 verbose parsed url   search: null,
6 verbose parsed url   query: null,
6 verbose parsed url   pathname: 'nan',
6 verbose parsed url   path: 'nan',
6 verbose parsed url   href: 'nan' }
7 silly lockFile 11e623a3-nan nan
8 error Error: Attempt to unlock nan, which hasn't been locked
8 error     at unlock (/usr/share/npm/lib/utils/locker.js:44:11)
8 error     at cb (/usr/share/npm/lib/cache/add-local.js:30:5)
8 error     at /usr/share/npm/lib/cache/add-local.js:47:20
8 error     at /usr/share/npm/lib/utils/locker.js:22:20
8 error     at /usr/share/npm/node_modules/inflight/inflight.js:22:7
8 error     at Array.forEach (native)
8 error     at res (/usr/share/npm/node_modules/inflight/inflight.js:21:9)
8 error     at /usr/lib/nodejs/once.js:17:15
8 error     at afterMkdir (/usr/share/npm/lib/cache/get-stat.js:53:14)
8 error     at /usr/lib/nodejs/mkdirp/index.js:46:53
9 error If you need help, you may report this *entire* log,
9 error including the npm and node versions, at:
9 error     <http://github.com/npm/npm/issues>
10 error System Linux 4.1.19-v7+
11 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "nan"
12 error cwd /usr/local/lib/node_modules/node-dht-sensor
13 error node -v v0.10.29
14 error npm -v 1.4.21
15 verbose exit [ 1, true ]

**Comment by goog** [comment]
solved by 
```bash
pi@raspberrypi:~ $ sudo npm install -g npm
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm@3.8.6 /usr/local/lib/node_modules/npm
pi@raspberrypi:~ $ sudo npm install -g node-dht-sensor
npm WARN lifecycle node-dht-sensor@0.0.11~preinstall: cannot run in wd %s %s (wd=%s) node-dht-sensor@0.0.11 ./preinst /usr/lib/node_modules/.staging/node-dht-sensor-c5090858
/usr/lib
└─┬ node-dht-sensor@0.0.11 
  └── nan@2.2.1 
```
