### ISSUE TITLE
Cannot find module Error

### ISSUE THREAD

**Issue by naromwerd** [momenso/node-dht-sensor#41]
I've every combination that I can think of to install node-dht-sensor but every time I run the test.js it fails with the following error. I little help would be most appreciated! 

Thanks.

pi@raspberrypi:~/node_modules/node-dht-sensor $ sudo node test.js
module.js:440
    throw err;
    ^

Error: Cannot find module './build/Release/node_dht_sensor'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/node_modules/node-dht-sensor/test.js:5:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)

**Comment by naromwerd** [comment]
OK sorry folks I think I missed this! Got it to work using the node-gyp commands!

Got it to work as follows: maybe it will help some poor soul

       INSTALL THE BCM2835:
	wget http://www.airspayce.com/mikem/bcm2835/bcm2835-1.50.tar.gz
	tar zxvf bcm2835-1.50.tar.gz
	cd bcm2835-1.50
	./configure
	make
	sudo make check
	sudo make install

	INSTALL NODEJS and NPM
	curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
	sudo apt-get install -y nodejs
	
        NODE-DHT-SENSOR
	sudo npm install node-dht-sensor
	goto the directory /home/pi/node_modules/node-dht-sensor
	node-gyp configure
	node-gyp build
	run the program
	sudo node test.js
