### ISSUE TITLE
Install Problem 

### ISSUE THREAD

**Issue by abataille** [momenso/node-dht-sensor#56]
I have a problem with the install. 
Here is the list of the errors I get:

pi@raspberrypi:~ $ sudo npm install node-dht-sensor
npm WARN lifecycle node-dht-sensor@0.0.31~preinstall: cannot run in wd %s %s (wd=%s) node-dht-sensor@0.0.31 ./check-lib.sh /home/pi/node_modules/.staging/node-dht-sensor-cfd4dcc2

> node-dht-sensor@0.0.31 install /home/pi/node_modules/node-dht-sensor
> node-gyp configure

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.7.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/node_modules/node-dht-sensor/.node-gyp"

> node-dht-sensor@0.0.31 postinstall /home/pi/node_modules/node-dht-sensor
> node-gyp build

make: Entering directory '/home/pi/node_modules/node-dht-sensor/build'
make: *** No rule to make target '../.node-gyp/6.7.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/home/pi/node_modules/node-dht-sensor/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.13+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/pi/node_modules/node-dht-sensor
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm ERR! Linux 4.4.13+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "node-dht-sensor"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! node-dht-sensor@0.0.31 postinstall: `node-gyp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-dht-sensor@0.0.31 postinstall script 'node-gyp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-dht-sensor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-dht-sensor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-dht-sensor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

BCM2385 is already installed.

**Comment by abataille** [comment]
I solved it. You have to install it with --unsafe-perm
